### ISSUE TITLE
Unable to autofill with Dashlane when AdGuard for Safari is running

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardForSafari#266] opened 2019-09-29 09:23 UTC
I'm using AdGuard for Safari to block Ads in Safari. Unfortunately, it happens very often that the autofill feature of Dashlane is not working in Safari when AdGuard for Safari is active. Could you please investigate this?

System information

- macOS Mojave 10.14.6
- Safari 13.0 (14608.1.49)
- Dashlane 6.1935.0.22755 (standalone installation, not AppStore)
- Dashlane Safari extension 6.1935.0
- AdGuard helpdesk ID **1516824**

**Comment by Eugene-Savenko** [comment] 2019-09-29 09:23
Here's what the Dashlane support says about that:

> understand when AdGuard is enabled you have issues with Dashalne autofilling the information. Adguard can make a conflict Dashlane and block the application functionality. Sadly, we do not have a solution for that.kindly contact Adguard support if they can white-list the Dashlane from their application

**Comment by SoLenny** [comment] 2019-10-03 13:05
@Mizzick Seems like it's not reproduce on my side.
AdGuard for Safari does not interfere with correct operation.

@Eugene-Savenko Can u maybe describe additional details? Everything works for me correctly.

**Comment by SoLenny** [comment] 2019-10-16 10:30
It's still not reproducible on our side, so i close this issue for now.
If similar incidents occur again, you can reopen the task.

**Comment by ovflowd** [comment] 2020-05-13 21:53
Hey, sorry for bumping this one. But it seems that AdGuard is indeed interfering with Dashlane.

Disabling the AdGuard Filtering in one Page (Using the Assistant) does make Dashlane work.

**Comment by ovflowd** [comment] 2020-05-14 07:49
If it’s useful I may gather some logs 🙂

**Comment by ameshkov** [comment] 2020-05-14 08:30
> Disabling the AdGuard Filtering in one Page (Using the Assistant) does make Dashlane work.

Could you please say what page exactly?

**Comment by ovflowd** [comment] 2020-05-14 12:42
@ameshkov it's hard to point out, since, it seems to happen only certain times. It's not something that happens always.

I may be wrong also, and this Issue is not entirely related to AdGuard at all. I will do further investigation before bothering you folks again.

Anyways, thanks!

**Comment by ovflowd** [comment] 2020-06-01 10:54
Here we go:

![image](https://user-images.githubusercontent.com/12037269/83402293-bfa14e00-a406-11ea-80cb-86f493060696.png)

The page is https://auth.adguard.com

The extension is enabled but is not auto-filling.

But after closing Safari and reopening, it auto-filled.

**Comment by ovflowd** [comment] 2020-06-04 16:09
I was finally able to generate a HAR. For some strange reasons when this bug happens, the whole "Web Inspector" (Developer Tools) of Safari, "stops working". The buttons are just not clickable, like if they were only read-only.

[www.serasa.com.br.har.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/4731301/www.serasa.com.br.har.zip)

Also here are the enabled Safari Extensions:

![image](https://user-images.githubusercontent.com/12037269/83781190-75ca9900-a68e-11ea-9402-55da781c697f.png)

**Comment by ameshkov** [comment] 2020-06-04 16:15
@ovflowd thank you! I've hidden the har file from your comment just in case

**Comment by ovflowd** [comment] 2020-06-04 16:18
Sure! I know the `har` has sensitive data. Thanks for the eager answer!

I'm almost sure it's an extension conflict since both of the extensions rewrite the DOM.

I can see for an instance of second the Dashlane extension loading into the Form Inputs, and then disappearing...

Not sure if it is related. And it happens just sometimes. To fix this issue, sometimes I need to restart Safari, sometimes I need to just close and reopen the tab. It is indeed a true mystery.

**Comment by ovflowd** [comment] 2020-06-04 17:54
1. 2.4.8.797 release (CL-1.5.269)

2. ![image](https://user-images.githubusercontent.com/12037269/83793570-08723480-a69d-11ea-8362-9a1c1ff4acbb.png)

Also these extra-settings: 

![image](https://user-images.githubusercontent.com/12037269/83793673-2dff3e00-a69d-11ea-8549-45a5a336bd87.png)

![image](https://user-images.githubusercontent.com/12037269/83793683-322b5b80-a69d-11ea-8340-0de9b648d1ad.png)

**Comment by ameshkov** [comment] 2020-06-04 17:57
Oh, so it's AG for Mac, we thought that this is about the Safari extension at first.

Hopefully, we'll be able to reproduce this

**Comment by ovflowd** [comment] 2020-06-04 18:06
@ameshkov I actually had the AdGuard Safari Installed, thought it was the Issue, then removed it.

The issue persists. But yes, I guess it wasn't a problem of the Safari Extension then. (Or may be also, not sure)....

**Comment by ovflowd** [comment] 2020-06-06 14:29
![image](https://user-images.githubusercontent.com/12037269/83946501-98d18600-a811-11ea-8e3f-9aec8b110262.png)

Some console logs.

**Comment by zzebrum** [comment] 2020-06-17 14:23
@ovflowd right at that time when I recorded the video https://uploads.adguard.com/screencast_2020-06-17_17-06-23.mp4 the problem became reproducible, but it occurs very rarely.

please, try to disable Stealth mode in AdGuard settings and check the issue in Safari.

**Comment by ovflowd** [comment] 2020-06-17 14:29
Will do it and do some tests. Thanks for the feedback!.

Here it depends, sometimes it is indeed rare, other times it repeats often. It even feels random somehow.

**Comment by zzebrum** [comment] 2021-06-04 10:05
@ovflowd wow 🙈 , it's been a year now! is it still an issue?

**Comment by ovflowd** [comment] 2021-06-04 10:34
That's a good question. Honestly, I'm not using Dashlane anymore since the problem was mostly on their side. With 1Password everything works fine.

I would probably label this as a Wont-Fix. But thank you anyways for the care ❤️

**Closed** 2021-06-04 10:36 UTC
Labels: Cannot reproduce, Question, Resolution: Won't Fix, Status: Resolved, Wontfix
