### ISSUE TITLE
Dark mode switches to light mode on Google.com

### ISSUE THREAD

**Issue by celphirio980** [AdguardTeam/AdGuardForSafari#891] opened 2023-09-18 02:23 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: Ventura 13.5.2
- Safari version: 16.6
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Fanboy's Annoyances, Online Malicious URL Blocklist, NoCoin Filter List

### Issue Details

Steps to reproduce:
1. Open Google.com
2. Enable Google's native dark mode
3. Enter a search term, click on an image, anything that keeps you on the Google startpage, images, maps, etc.
4. The screen will turn white--as if dark mode was disabled. Dark mode is still enabled, though, and refreshing the page fixes it temporarily

### Expected Behavior

Dark mode shouldn't change at all

### Actual Behavior

Dark mode changes to light mode

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

It might be Dark Reader which changes pages, but nothing has changed with that app and there hasn't been an update. I keep it disabled by default on Google.com (the only site where this happens) as I use Google's native dark mode setting. I suspect it may be AdGuard since I changed filters recently. I could be wrong. Thanks!

**Comment by alexx7311** [comment] 2023-09-18 09:46
@celphirio980 We couldn't reproduce the problem. Please disable all other Safari extensions and try to reproduce the problem again. If you record a video, that would be very helpful to us.

**Comment by alexx7311** [comment] 2023-10-02 09:16
@celphirio980 We'll close the issue for now. If your problem reproduces, you can reopen it at any time.

**Closed** 2023-10-02 09:16 UTC
Labels: Priority: P4

**Comment by Frerduro** [comment] 2023-11-13 04:56
I am having this issue. If I don't use google for a few hours it switches to light mode, Reloading the page immediately fixes the issue for me for a few hours then its rinse and repeat. I am using windows 11 and adguard desktop with adguard assistant installed on chrome.

**Comment by celphirio980** [comment] 2023-11-13 14:00
Sorry, I forgot to update this thread. The problem stopped after a major recent update to Dark Reader for Safari, might work for Chrome or another browser. Update Dark Reader if you have it, or use an alternative like Noir (I didn't have this issue with Noir)
