### ISSUE TITLE
AdGuard keeps popping all day long

### ISSUE THREAD

**Issue by jimen1** [AdguardTeam/AdGuardForSafari#792] opened 2023-01-28 05:31 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version: 1.11.9
- [x] I checked the documentation and found no answer: yes
- [x] I checked to make sure that this issue has not already been filed: doesn't matter, still have the issue

### Issue Details

* AdGuard for Safari version: again 1.11.9
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)): exactly this version
* Operating System: (e.g macOS High Sierra 10.13.6) 13:1. Ventura
* Filters you use in AdGuard: default
* Any other browser extensions you have installed: no

* **Version of AdGuard for Safari:**
  *  again 1.11.9
* **Environment name and version:**
  *  again 11.2
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:** again 13.1 Ventura
  * 
* **Any other browser extensions you have installed:**
  *  no

### Expected Behavior

AdGuard shouldn't pop 2-3 times a day.  

### Actual Behavior

Ad Guard pops 2-3 times a day..

### Screenshots

<details><summary>Screenshot:</summary>

Ad Guard pops 2-3 times a day..

</details>

### Additional Information
 Why is this not working?

**Comment by jimen1** [comment] 2023-01-28 05:33
While I have to check the boxes you ask for. There's no other way. I'm not a computer expert. My son installed this. All this got me here. I'm 61 years old and no need for other stuff.

**Comment by Versty** [comment] 2023-01-30 09:10
@jimen1 Hi! 
Please, update to the latest version (1.11.10), this should fix the issue.

**Comment by Versty** [comment] 2023-01-30 09:17
@jimen1 This issue is a duplicate of #746 
Please move the discussion there.

**Closed** 2023-01-30 09:23 UTC
Labels: Bug
