### ISSUE TITLE
Custom rules not working after update to 1.8.6

### ISSUE THREAD

**Issue by technocoreai** [AdguardTeam/AdGuardForSafari#439] opened 2020-11-24 23:15 UTC
### Issue Details

* AdGuard for Safari version: Version 1.8.6
* Environment name and version: (e.g. Safari 14.0.1 (16610.2.11.51.8))
* Operating System: (e.g macOS Big Sur 11.0.1)
* Filters you use in AdGuard: Base filter, Tracking Protection filter, Social Media filter, Annoyances filter, Russian filter
* Any other browser extensions you have installed: Cascadea, StopTheMadness, TamperMonkey

### Expected Behavior

User rules continue working after an update to 1.8.6.

### Actual Behavior

After an update from 1.8.2 to 1.8.6, user rules have completely stopped working. I've tried disabling and reenabling extensions, disabling and reenabling filters, clicking the reload button, removing the user rules and adding them back one by one, but this doesn't seem to help. Other filters seem to work fine.

There are no obvious errors reported in the applications' log. For some reason the user rules seem to be converted and applied twice, both for the Other and Custom extensions, but disabling one of the extensions in Safari doesn't seem to fix anything.

<details>
<summary>Application log (only custom/other/end result)</summary>

    [2020-11-25 00:07:28.350] [info] ConverterTool version: v1.1.2
    [2020-11-25 00:07:28.350] [info] Conversion of 11 rules started..
    [2020-11-25 00:07:28.351] [info] Running converter from: /Applications/AdGuard for Safari.app/Contents/Resources/libs/ConverterTool
    [2020-11-25 00:07:28.371] [info] Conversion of 11 rules completed.
    [2020-11-25 00:07:28.372] [info] Rules converted:  11 (0 errors)
    Basic rules: 1
    Basic important rules: 0
    Elemhide rules (wide): 0
    Elemhide rules (generic domain sensitive): 0
    Exceptions Elemhide (wide): 0
    Elemhide rules (domain-sensitive): 4
    Script rules: 0
    Scriptlets rules: 0
    Extended Css Elemhide rules (wide): 0
    Extended Css Elemhide rules (generic domain sensitive): 0
    Extended Css Elemhide rules (domain-sensitive): 0
    Exceptions (elemhide): 0
    Exceptions (important): 0
    Exceptions (document): 0
    Exceptions (jsinject): 0
    Exceptions (other): 0
    [2020-11-25 00:07:28.373] [info] Setting content blocker json for com.adguard.safari.AdGuard.BlockerOther.Rules count: 5. Json length=805;
    [2020-11-25 00:07:28.373] [info] ConverterTool version: v1.1.2
    [2020-11-25 00:07:28.374] [info] Conversion of 11 rules started..
    [2020-11-25 00:07:28.374] [info] Running converter from: /Applications/AdGuard for Safari.app/Contents/Resources/libs/ConverterTool
    [2020-11-25 00:07:28.400] [info] Conversion of 11 rules completed.
    [2020-11-25 00:07:28.401] [info] Rules converted:  11 (0 errors)
    Basic rules: 1
    Basic important rules: 0
    Elemhide rules (wide): 0
    Elemhide rules (generic domain sensitive): 0
    Exceptions Elemhide (wide): 0
    Elemhide rules (domain-sensitive): 4
    Script rules: 0
    Scriptlets rules: 0
    Extended Css Elemhide rules (wide): 0
    Extended Css Elemhide rules (generic domain sensitive): 0
    Extended Css Elemhide rules (domain-sensitive): 0
    Exceptions (elemhide): 0
    Exceptions (important): 0
    Exceptions (document): 0
    Exceptions (jsinject): 0
    Exceptions (other): 0
    [2020-11-25 00:07:28.401] [info] Setting content blocker json for com.adguard.safari.AdGuard.BlockerCustom.Rules count: 5. Json length=805;
    [2020-11-25 00:07:28.405] [info] ConverterTool version: v1.1.2
    [2020-11-25 00:07:28.406] [info] Conversion of 72906 rules started..
    [2020-11-25 00:07:28.406] [info] Running converter from: /Applications/AdGuard for Safari.app/Contents/Resources/libs/ConverterTool
    [2020-11-25 00:07:28.548] [info] Content-blocker com.adguard.safari.AdGuard.BlockerCustom set result : {"result":"success", "dataLenght":"805"}
    [2020-11-25 00:07:28.548] [info] Content-blocker com.adguard.safari.AdGuard.BlockerOther set result : {"result":"success", "dataLenght":"805"}
    [2020-11-25 00:07:28.603] [info] Content-blocker com.adguard.safari.AdGuard.BlockerPrivacy set result : {"result":"success", "dataLenght":"1389526"}
    [2020-11-25 00:07:29.331] [info] Content-blocker com.adguard.safari.AdGuard.BlockerSocial set result : {"result":"success", "dataLenght":"1432505"}
    [2020-11-25 00:07:30.050] [info] Content-blocker com.adguard.safari.AdGuard.BlockerExtension set result : {"result":"success", "dataLenght":"4111408"}
    [2020-11-25 00:07:31.225] [info] Conversion of 72906 rules completed.
    [2020-11-25 00:07:31.272] [info] Rules converted:  69030 (255 errors)
    Basic rules: 25586
    Basic important rules: 41
    Elemhide rules (wide): 30
    Elemhide rules (generic domain sensitive): 1116
    Exceptions Elemhide (wide): 2247
    Elemhide rules (domain-sensitive): 9829
    Script rules: 2531
    Scriptlets rules: 1665
    Extended Css Elemhide rules (wide): 0
    Extended Css Elemhide rules (generic domain sensitive): 0
    Extended Css Elemhide rules (domain-sensitive): 3049
    Exceptions (elemhide): 28
    Exceptions (important): 7
    Exceptions (document): 146
    Exceptions (jsinject): 16
    Exceptions (other): 5856
    [2020-11-25 00:07:31.273] [info] Setting content blocker json for com.adguard.safari.AdGuard.AdvancedBlocking.Rules count: 44905. Json length=3186485;
    [2020-11-25 00:07:31.298] [info] Content-blocker com.adguard.safari.AdGuard.AdvancedBlocking set result : {"result":"success"}

</details>

### Additional Information

A couple of example rules I use:

    reddit.com ## #redesign-beta-optin-btn
    reddit.com ## .premium-banner-outer
    twitch.tv ## .prime-offers

Rolling back to 1.8.2 has helped, so it seems like a bug in 1.8.6.

**Comment by ameshkov** [comment] 2020-11-25 19:06
Could you please check with the latest beta version?

There are some quite important changes there:
https://agrd.io/safari_beta

**Comment by ameshkov** [comment] 2020-11-25 19:07
Oh, and a note about the rules, the proper syntax is:
```
reddit.com###redesign-beta-optin-btn
reddit.com##.premium-banner-outer
twitch.tv##.prime-offers
```

**Comment by technocoreai** [comment] 2020-11-25 19:16
Don't see any issues with the beta version, thanks!

**Comment by ameshkov** [comment] 2020-11-25 19:17
Awesome, thank you!

I'll mark it as duplicate because most likely the original issue was caused by some other bug fixed in this beta :)

**Closed by ameshkov** 2020-11-25 19:17 UTC
Labels: Duplicate
