### ISSUE TITLE
High Sierra and Safari Converter Lib

### ISSUE THREAD

**Issue by Keydance** [AdguardTeam/AdGuardForSafari#419] opened 2020-11-17 11:48 UTC
### Issue Details

* AdGuard for Safari version: 1.8.5
* Environment name and version: Safari 13.1.2 (13609.3.5.1.5)
* Operating System: macOS High Sierra 10.13.6
* Filters you use in AdGuard: all recommended

### Expected Behavior
Loading filters normally – especially when I push the update button.

### Actual Behavior
No filters are getting loaded since 1.8.5 anymore. Before everything worked fine. No change after un- & reinstall.
I checked the last version (via Time Machine) before 1.8.5 = 1.8.2 (this works fine).

### Screenshot
![2020-11-17 at 12 33](https://user-images.githubusercontent.com/74599586/99385882-e4fd1800-28d1-11eb-8b1a-f92c6e964358.png)

### Additional Information
Hello everybody,
I joined this forum to report a bug.
I appreciate if somebody could help me somehow – thank you.
Best wishes
Jens

**Comment by ameshkov** [comment] 2020-11-18 07:11
The problem is that we can't support high sierra anymore, you'll need to downgrade to v1.7.x

**Comment by Keydance** [comment] 2020-11-18 08:46
Thanks for your reply. v1.8.2 works for now, but I do not know how long.
How can I downgrade to v1.7.x? I have no backup of this version.

**Comment by ameshkov** [comment] 2020-11-18 08:47
Oh, if v1.8.2 works that's okay, we'll look into it.

**Comment by ameshkov** [comment] 2020-11-18 08:48
@Mizzick please check if there's an easy way to make SafariConverterLib work on High Sierra.

**Comment by Keydance** [comment] 2020-11-18 08:51
Yes, v1.8.2 works on High Sierra. Thanks for trying.

**Comment by Keydance** [comment] 2020-11-19 11:28
Quick feedback: same issue with 1.8.**6** on High Sierra – still no filter download.

**Comment by ameshkov** [comment] 2020-11-19 12:23
The next update should fix it

**Comment by Keydance** [comment] 2020-11-19 12:53
That's great – thanks.

**Comment by nmt1900** [comment] 2020-11-20 14:49
1.8.5 "almost" worked on High Sierra, but was complaining about disabled extensions at least filters loaded and worked. 

With v1.8.6 most of extensions are missing from Safari and filters are not loaded at all. If Adguard is released on Mac App Store as compatible with 10.12 and newer and this version got also released as such, then it makes app unusable after update. With older releases being unavailable - for some inexplicable reason - it makes Safari unusable.

Why hide older releases?

**Comment by crgmrgn** [comment] 2020-11-20 17:04
Similar issue here, was running 1.8.2 from the AppStore (which seemed to be fine), then the 1.8.5 release gave rise to the SafariConvertorLib failure and failure of some rulesets but still a basically operational toolset. Now the 1.8.6 release has completely stymied opertaion as only 3x extensions now even show up in the Safari Extensions Preferences window, alongside the completel failure to accept any new rulesets.

So, for the time being I've had to disable the s/w pending your fixes, but it doesn't look good particularly for site deployments on colleagues machines.

**Comment by ameshkov** [comment] 2020-11-23 20:24
Sorry for the issues. The change in v1.8.5-1.8.6 is rather massive, we've started using a new "rules converter" library, now written in Swift instead of JS. It provides some nice perks - improved compilation speed, better optimization, etc. Unfortunately, we missed some of the important cases (high sierra support being one of them). We're trying our best to resolve them all asap.

**Comment by jimmysofat6864** [comment] 2020-11-25 04:05
How do we downgrade the app? I tried going to the releases page but it only downloads the latest version no matter which one I click.

**Comment by ameshkov** [comment] 2020-11-25 08:19
@jimmysofat6864 the beta version with High Sierra should be available later today

**Comment by ameshkov** [comment] 2020-11-25 19:15
Hey everyone, please try the latest beta version, it should work okay in High Sierra: https://agrd.io/safari_beta

**Comment by jimmysofat6864** [comment] 2020-11-25 19:36
I have tested it and so far, the only thing that doesn't seem to work for me is the refresh filters button and the filter refresh time being 19 hours out of sync.

**Comment by crgmrgn** [comment] 2020-11-25 19:46
I'd concur … quick check show rules operative, extensions are all back in place in Safari and enabled, "check for filter updates" from the menubar seems to work correctly but the refresh filters icon in the app is no longer responsive.

Reddit and Youtube comment section scrolling seems to be back to a manageable speed.

**Comment by ameshkov** [comment] 2020-11-25 19:46
> I have tested it and so far, the only thing that doesn't seem to work for me is the refresh filters button and the filter refresh time being 19 hours out of sync.

Yep, known issue of this beta version. 

For now, you can use the menu bar, or you can actually click that button (there's a small area under the button that is still clickable :))

**Comment by crgmrgn** [comment] 2020-11-25 19:48
Ha ha, the small area might well be present (I note the cursor change when in place) but a click does not register any action! ;)

**Comment by jimmysofat6864** [comment] 2020-11-25 20:28
The menu bar was able to refresh the ad lists and the time is now in sync now. Also I don't have that issue about parts being disabled as they all now show up in the preferences pane.

**Comment by nmt1900** [comment] 2020-11-27 17:46
With 1.8.8 Beta Adguard Security is still in disabled state and nowhere to be found in Safari Extensions window. All attempts to clear all settings and start from scratch have been unsuccesful so far...

Safari 13.1.2 (13609.3.5.1.5)
macOS 10.13.6 (17G14042)

**Comment by ameshkov** [comment] 2020-11-28 08:29
@nmt1900 I wonder if this is a Safari glitch? Please try re-installing AdGuard

**Comment by Keydance** [comment] 2020-11-28 13:43
Today I tested 1.8.8 from the App Store and so far it seems to work fine – thank you so much for fixing it!!

**Closed** 2020-11-30 09:23 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved
