### ISSUE TITLE
Settings panel opens at login (again!) [same as closed #746]

### ISSUE THREAD

**Issue by Perifractic** [AdguardTeam/AdGuardForSafari#853] opened 2023-05-25 02:39 UTC
The bug with settings panel opening at login has returned. Previously has been fixed in #746. 

The settings panel opens every time the Mac wakes, requiring the user to close the AdGuard window every time they sit down at their computer.

<details><summary> Original text </summary>

### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
Safari / Mac
```

### Issue Details

You have once again reintroduced the exact same bug from closed bug #746 where the settings panel opens every time the Mac wakes, requiring the user to close the AdGuard window every time they sit down at their computer.

This was solved before, then broken again, then solved again, then the bug closed (746), now you've broken it again.

Whoever keeps reintroducing this bug, please stop them! It is beyond frustrating.

AdGuard is meant to stop annoying popups and ads, yet AdGuard ITSELF has BECOME an annoying popup. I have to close it perhaps 10 times a day. Please urgently fix, and fix forever.

### Expected Behavior

See above and #746

### Actual Behavior

See above and #746 

### Screenshots

See #746

</details>

**Comment by Versty** [comment] 2023-05-28 13:44
@Perifractic Hi! What is your MacOS version? 
We have tried to reproduce this issue with 13.3.1, but to no avail. Works fine on our side. 

Also, we would like you to check if the `com.adguard.safari.AdGuard.plist` file is in the list in the `~/Library/Preferences` folder on your device. (Open Finder -> Press command+shift+G -> enter ~/Library/Preferences)

**Comment by Perifractic** [comment] 2023-05-28 16:06
Last time this happened you also said you couldn't reproduce it, then eventually fixed it. Then unfixed it.

I have 13.4 (22F66).

There is no AdGuard file in Preferences.

As [others are now also reporting](https://github.com/AdguardTeam/AdGuardForSafari/issues/680#issuecomment-1566143037) the bug is not fixed, I doubt it's an issue with my system.

**Comment by Versty** [comment] 2023-05-30 16:04
@timlockridge Could you specify your MacOS version, chip and Safari version?

**Comment by EvanGrote** [comment] 2023-05-30 16:13
I'm seeing this behavior on both of my macOS devices:

MacOS Version: Ventura 13.4
Chip: M2 Pro
Safari Version: 16.5 (18615.2.9.11.4)

MacOS Version: Ventura 13.4
Chip: M2
Safari Version: 16.5 (18615.2.9.11.4)

**Comment by timlockridge** [comment] 2023-05-30 16:23
> @timlockridge Could you specify your MacOS version, chip and Safari version?

MacOS Version: Ventura 13.4
Chip: 3.4 GHz Quad-Core Intel Core i5
Safari Version: Version 16.5 (18615.2.9.11.4)

**Comment by Versty** [comment] 2023-05-30 16:27
@timlockridge @EvanGrote Thank you! 

Have you updated from the previous version or installed the application for the first time?

**Comment by timlockridge** [comment] 2023-05-30 17:27
> I updated from the previous version. Currently running Version 1.11.13 (build 297, CT 2.0.39)

Same here

**Comment by Versty** [comment] 2023-06-19 12:17
@Perifractic @EvanGrote @timlockridge 
Please make sure that AdGuard for Safari is not in the `Open at Login` list in the system settings. 

*System settings -> General -> Login items*

**Comment by Richipedia** [comment] 2023-06-20 09:35
Seeing this again on my system too. It was fixed for a while but now is happening when my Mac wakes from sleep.

macOS version: 13.4 (22F66)
Safari version: 16.5 (18615.2.9.11.4)
AdGuard version: 1.11.12 (build 289, CT 2.0.34)

I can confirm that AdGuard for Safari is not listed in Open at Login in my System Settings.

I have submitted by AdGuard logs via email.

**Comment by Versty** [comment] 2023-06-20 10:27
@Richipedia Thanks! Got the logs from you.

**Comment by sonnykt** [comment] 2023-07-25 03:43
The settings window not only opens when my mac wakes up but also at random time during the day while I am using the mac.

macOS version 13.4.1 (c) (22F770820d)
Safari Version 16.5.2 (18615.2.9.11.10)
AdGuard version: Version 1.11.12 (build 289, CT 2.0.34)

**Comment by probably-carly1** [comment] 2023-07-27 00:50
I also have this issue, it's rather bothersome as I almost never want to see the settings panel. This should be a "set it and forget it" situation.

macOS version 13.4.1 (22F82)
Safari Version 16.5.2 (18615.2.9.11.10)
AdGuard version 1.11.12 (build 289, CT 2.0.34)

Happy to provide any extra details.

**Comment by Perifractic** [comment] 2023-08-03 21:31
It just started happening AGAIN 2 days ago. This is getting beyond ridiculous. Please address this at a high level with your engineers.

**Comment by huyfam** [comment] 2023-08-05 04:06
Confirmed. It's back. The window shows up when I wake up my Mac.

**Comment by pawelwiejkut** [comment] 2023-08-06 07:58
Same for me. Issue is back.

**Comment by yd021976** [comment] 2023-08-09 07:55
Hi all, same here. The control panel opens randomly in the day. Either after I wake up my Mac from sleep, either when I'm using it.

**Comment by hch0u** [comment] 2023-08-14 12:55
Same issue here.

AdGuard version: 1.11.13 (build 297, CT 2.0.39)
Safari version: 16.6 (18615.3.12.11.2)
macOS version: 13.5 (22G74)

**Comment by hch0u** [comment] 2023-08-14 12:58
> Same issue here.
> 
> ```
> AdGuard version: 1.11.13 (build 297, CT 2.0.39)
> Safari version: 16.6 (18615.3.12.11.2)
> macOS version: 13.5 (22G74)
> ```

Updated to `Version 1.11.14 (build 301, CT 2.0.41)`, issue persists.

**Comment by vozersky** [comment] 2023-08-29 15:58
Also reported:
https://github.com/AdguardTeam/AdGuardForSafari/issues/875
https://github.com/AdguardTeam/AdGuardForSafari/issues/875
https://github.com/AdguardTeam/AdGuardForSafari/issues/880

**Comment by alexx7311** [comment] 2023-08-31 09:56
@benfischer1 @prophoto @hch0u @yd021976 @pawelwiejkut @huyfam @Perifractic @probably-carly1 @sonnykt @Richipedia @Perifractic @EvanGrote @timlockridge

Please do the following:

1. Open Terminal: You can find Terminal in the Utilities folder within the Applications folder.

2. Enter the Following Command:
`/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump > lsregister_dump.txt`

3. Run the Command: Press **Enter** to execute the command. This will dump the data and save it into a file named lsregister_dump.txt in the current directory.

4. Optional: If you encounter permission issues, prepend the command with `sudo` and then enter your password when prompted.

Then navigate to the current directory in the Terminal or Finder, find lsregister_dump.txt and send the file to `apple@adguard.com` and mention in the subject the issue number `853`

**Comment by EvanGrote** [comment] 2023-09-01 16:33
@alexx7311 Sent 👍🏽

**Comment by alexx7311** [comment] 2023-09-14 12:17
@benfischer1 @prophoto @hch0u @yd021976 @pawelwiejkut @huyfam @Perifractic @probably-carly1 @sonnykt @Richipedia @Perifractic @EvanGrote @timlockridge

Do you close this window before restart?
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/ba6c1bf6-8180-428e-8cca-884184fcd12e)

</details>

Does the AdGuard window with settings appear every time you restart your system?

Please send a video of reproducing the problem if possible.

Also please do the following:
1) Restart your system to reproduce the problem
2) Once you see the AdGuard for Safari settings window open (**no more than 10 minutes should pass, otherwise the log will not contain the necessary information**), open Terminal and type the following:
`log show --info --last 10m | grep -i "adguard" > log.txt`
3) Press Enter to execute the command.
4) Open AdGuard for Safari settings > General > 'Export logs' > 'Save'

Then find log.txt file and saved AdGuard for Safari logs and send them to `apple@adguard.com` and mention in the subject the issue number `853`

**Comment by Perifractic** [comment] 2023-09-22 05:13
I have to agree. The way you guys are handling this tiny bug is bizarre. It's been open for one year today (original ticket: https://github.com/AdguardTeam/AdGuardForSafari/issues/746 )

It's quite simple: If I leave the Mac alone (even with the screen on!) for around 10 minutes, the AdGuard window pops up. So you guys just need to figure out what you're triggering when there's no mouse activity for 10 mins. Then stop that.

**Comment by Versty** [comment] 2023-10-03 11:59
@Perifractic @emmetbroaders @EvanGrote @hch0u @pawelwiejkut @yd021976 @Richipedia @huyfam @probably-carly @sonnykt @timlockridge 

Hi everyone!  

We understand your feelings and have done our best to fix this bug (again!). Beta version (1.11.15) is already available to test in the TestFlight. Starting from this version, AdGuard for Safari will launch in the background in most scenarios, _random_ popups of the settings window should be gone as well. 
Feel free to try it out and share any feedback. 

[How to join beta](https://adguard.com/en/beta.html?platform=safari)

**Comment by Otider** [comment] 2023-10-05 03:35
Experiencing this issue on a MacBook Pro M1 running Ventura 13.5.2 (22G91), Safari Version 16.6 (18615.3.12.11.2), Ad Guard Version 1.11.13 (build 297, CT 2.0.39). Settings window pops up every time I restart. Please fix.

**Comment by Versty** [comment] 2023-10-09 14:46
@Otider Please update to the latest version (AdGuard for Safari 1.11.15) and let us know the result.

**Closed** 2023-10-11 09:02 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Priority: P2, Version: Safari v1.11.15

**Comment by collectttive** [comment] 2023-10-14 07:26
It is **not** fixed.

**Comment by sonnykt** [comment] 2023-10-15 22:48
It's still happening on Version 1.11.12 (build 289, CT 2.0.34) with latest Safari on macOS Sonoma.

**Comment by Perifractic** [comment] 2023-10-16 00:06
@Versty Please don't close my tasks or let the bot close them when they are not fixed.

**Comment by yd021976** [comment] 2023-10-16 09:30
Hi, I confirm that with version 1.11.15 (and not 1.11.12 that is not the last version), the bug is fixed for me. No more setting window appearing since installing v1.11.15 (five or six days ago).
My environnement is : Mac mini M2 pro, MacOS Sonoma, Safari 17.0, Adguard for Safari v1.11.15
@sonnykt : It seems you tested with 1.11.12 that is not the last version. Try with 1.11.15
@collectttive : Wich version of AdGuard for safari are you using ?

**Comment by Perifractic** [comment] 2023-10-16 17:06
@Versty Maybe it would be helpful to write here how to update AdGuard on Safari. There is no "Update" option to be found in the app or Safari settings. Only "Uninstall".

**Comment by emmetbroaders** [comment] 2023-10-16 18:34
> @Versty Maybe it would be helpful to write here how to update AdGuard on Safari. There is no "Update" option to be found in the app or Safari settings. Only "Uninstall".

@Perifractic App Store pal

**Comment by Perifractic** [comment] 2023-10-16 18:45
@emmetbroaders Thanks! There was me searching the actual app and Safari settings, totally forgetting extensions are in the App Store now.

**Comment by prophoto** [comment] 2023-10-16 18:58
People are awful rude around here. Sad!
