### ISSUE TITLE
Update the README logo for dark mode

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardForSafari#906] opened 2023-10-06 21:37 UTC
Logo on the README hasn't been updated for dark mode displays.

Similar to [this commit](https://github.com/AdguardTeam/AdguardForMac/commit/9ff130ccc36c825eb8a25ff01d0d27a3016219f2), so the same for this repo.

**Comment by Versty** [comment] 2023-10-09 15:47
@jslawler Hi! 
Duplicate of #893. Will be implemented soon.

**Closed** 2023-10-09 15:47 UTC
Labels: Priority: P4
