### ISSUE TITLE
Import of filter lists from Rakuten

### ISSUE THREAD

**Issue by Eagle5161** [AdguardTeam/AdGuardForSafari#937] opened 2023-11-28 04:31 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.15

### Environment

```markdown
- OS:14.1.1
- Safari version:17.1
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1.Add a custom filter list from https://www.rakuten.ca/static/cashback-shopping-whitelist?
2.
3.

### Expected Behavior

It would import the list 

### Actual Behavior

Error occurred
Unfortunately, your custom filter cannot be added due to an unexpected error.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment] 2023-12-05 08:52
@Eagle5161 Hello! We couldn't reproduce the problem.
Are you sure you have access to the website and the filter? You can try saving the filter as a file and then click 'Add custom filter' > 'Import file' and select the file you saved earlier.

**Comment by alexx7311** [comment] 2023-12-13 11:46
@Eagle5161 Is the problem still relevant?

**Comment by Eagle5161** [comment] 2023-12-13 11:48
I can’t test it now as I’m on vacation. I will respond when I’m back home in 2 months.
________________________________

**Comment by alexx7311** [comment] 2023-12-14 10:01
@Eagle5161 We'll close the issue for now, but if the problem recurs, please leave a comment here and we'll reopen it.

**Closed** 2023-12-14 10:02 UTC
Labels: Priority: P4
