### ISSUE TITLE
Ad Guard Safari extension is still asking for update (once a week or more ofter) and killing all opened Safari tabs & windows

### ISSUE THREAD

**Issue by Mirek-CZ** [AdguardTeam/AdGuardForSafari#633] opened 2021-07-05 19:34 UTC
Ad Guard Safari extension is still asking for update (once a week or more ofter) and killing all opened Safari tabs & windows

### Steps to reproduce

1. after wake up a Mac from Sleep mode once twice a week pop up appeared: "Ad Guard for Safari need update" with buttons "Continue" and "Cancel".
2. if "Continue" then Ad Guard kills all opened tabs and windows of Safari and did something looking like update
3. but after launching all tabs and windows again and some time of work (couple of hours) again put Mac to sleep
4. once launched again back (woke up), Ad Guard again displays the same popup, repeatedly
5. so it seems that Ad Guard is 1. not doing the update properly and stupidly asking for update several times a day, 2. needs to kill all tabs and windows and restart of Safari, which is super annoying if you have the work in progress, you jus cannot close everything as it will be lost

### Expected behavior

1. update of Ad Guard shall be done in the background without need of Safari restart, or during the next system restart
2. update shall never ask to do several restarts of either system, or Safari, as it will repeatedly cause lost of time and work and money as well

### Actual behavior

- see description above

<details><summary>Screenshot:</summary>

can provide it next time

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): Safari Version 14.1.1 (16611.2.7.1.4), MacOS BigSur 11.4
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): No antivirus, no firewall, or other conflicting SW

**Comment by zzebrum** [comment] 2021-07-06 16:42
@Mirek-CZ AdGuard installed from App Store?

**Comment by tonimelisma** [comment] 2021-07-06 16:51
Yes @zzebrum, this is a duplicate of my bug and indeed I have installed Adguard from the App store.

**Comment by zzebrum** [comment] 2021-07-08 13:01
closed as dup #631

**Closed by zzebrum** 2021-07-08 13:01 UTC
