### ISSUE TITLE
App becomes completely unresponsive

### ISSUE THREAD

**Issue by Baccount** [AdguardTeam/AdGuardForSafari#330] opened 2020-03-19 23:41 UTC
### Issue Details

* AdGuard for Safari version: 1.7.1
* Environment name and version: (13.1 (15609.1.20.111.8))
* Operating System: (10.15.4 (19E264b))
* Filters you use in AdGuard: AdGuard Base filter,dGuard Social Media filter,Fanboy's Annoyances,Spam404,

### Expected Behavior
The app should not become unresponsive

### Actual Behavior
The app does become unresponsive at random

### Additional Information
I captured logs after the freeze occurred
[adg_safari_logs_1584660963944.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/4357337/adg_safari_logs_1584660963944.zip)

**Comment by ameshkov** [comment] 2020-03-22 11:29
Duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/331

**Closed by ameshkov** 2020-03-22 11:29 UTC
Labels: Duplicate
