### ISSUE TITLE
Compilation failing with NSRangeException

### ISSUE THREAD

**Issue by sammichaels** [AdguardTeam/AdGuardForSafari#1025] opened 2024-10-03 18:43 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.19 (build 335, CT 2.0.44)

### Browser version

Safari 18.0

### OS version

macOS Sequoia 15.0

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist, Scam Blocklist by DurableNapkin, uBlock Origin – Badware risks

### Which DNS server do you use?

System default DNS

### DNS protocol

Regular

### Custom DNS

iCloud Private Relay

### Issue Details

Steps to reproduce:
1. Notice ads appearing on websites
2. Go to General -> Content Blockers and notice "compilation error" on all of them
3. Export logs and notice the crash.

### Expected Behavior

The rules should compile

### Actual Behavior

The rules do not compile and the converter tool crashes.

### Additional Information

Mentioned in AdguardTeam/AdguardFilter#189795 thinking it was a filter issue, but dug deeper and found this.

Here is the log with the call stack:

```
[2024-10-03 13:09:22.081] [info] Setting content blocker json for advancedBlocking.Rules count: 120423. Json length=15925235;
[2024-10-03 13:09:22.083] [info] Content-blocker updating advancedBlocking
[2024-10-03 13:09:22.107] [info] Content-blocker advancedBlocking set result : {"result":"success"}
[2024-10-03 13:09:24.618] [info] Loading content blocker.
[2024-10-03 13:09:24.619] [info] Rules loaded: 135139
[2024-10-03 13:09:24.646] [info] Affinity block general: rules length: 27799
[2024-10-03 13:09:24.649] [info] Affinity block privacy: rules length: 38640
[2024-10-03 13:09:24.649] [info] Affinity block security: rules length: 10551
[2024-10-03 13:09:24.652] [info] Affinity block socialWidgetsAndAnnoyances: rules length: 27919
[2024-10-03 13:09:24.652] [info] Affinity block other: rules length: 40
[2024-10-03 13:09:24.652] [info] Affinity block custom: rules length: 37
[2024-10-03 13:09:24.653] [info] Detected Safari browser version: 18.0
[2024-10-03 13:09:24.653] [info] OS version: 15
[2024-10-03 13:09:24.653] [info] Converting for Safari version 18
[2024-10-03 13:09:24.653] [info] ConverterTool version: 2.0.44
[2024-10-03 13:09:24.653] [info] Conversion of 27799 rules started..
[2024-10-03 13:09:24.653] [info] CONVERTER PATH: /Applications/AdGuard for Safari.app/Contents/Resources/libs/ConverterTool
[2024-10-03 13:09:25.217] [error] Unexpected error converting rules: Error: *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFString rangeOfString:options:range:locale:]: Range {46, 18446744073709551608} out of bounds; string length 38'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000196408ec0 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000195eeecd8 objc_exception_throw + 88
	2   Foundation                          0x00000001974fef8c -[NSPathStore2 copy] + 0
	3   ConverterTool                       0x0000000104382b14 $s23ContentBlockerConverter11NetworkRuleC05parseE6DomainAC0G4InfoVSgyF + 980
	4   ConverterTool                       0x0000000104373320 $s23ContentBlockerConverter0B12EntryFactoryC24checkWhiteListExceptions33_C9BC5738408AC68EDABDCFBDD9FCB5F5LL4rule7triggeryAA11NetworkRuleC_AA0bD0V7TriggerVztKFTf4nnd_n + 108
	5   ConverterTool                       0x00000001043739c8 $s23ContentBlockerConverter0B12EntryFactoryC18convertNetworkRule33_C9BC5738408AC68EDABDCFBDD9FCB5F5LL4ruleAA0bD0VSgAA0gH0C_tKFTf4nd_n + 652
	6   ConverterTool                       0x0000000104376010 $s23ContentBlockerConverter8CompilerC12compileRules5rulesAA17CompilationResultVSayAA4RuleCG_tF + 1192
	7   ConverterTool                       0x000000010437c3c0 $s23ContentBlockerConverterAAC12convertArray5rules13safariVersion8optimize16advancedBlocking0jK6FormatAA16ConversionResultVSaySSG_AA06SafariH0OS2bAA08AdvancedkL0OtF + 620
	8   ConverterTool                       0x000000010430780c $s18CommandLineWrapper13ConverterToolV3runyyKF + 1448
	9   ConverterTool                       0x0000000104307ca0 $s18CommandLineWrapper13ConverterToolV14ArgumentParser08ParsableA0AadEP3runyyKFTW + 12
	10  ConverterTool                       0x0000000104306960 main + 96
	11  dyld                                0x0000000195f2c274 start + 2840
)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by windwak3r** [comment] 2024-10-11 14:55
@sammichaels, hello! Please disable all other extensions in Safari and try completely uninstalling AdGuard for Safari:

1. Uncheck all AdGuard for Safari extensions in `Safari - Preferences - Extensions`
2. Remove AdGuard for Safari application from Applications folder
3. In Finder press Shift+Command+G and remove following files:
- Remove **AdGuardSafariApp** folder from `~/Library/Application` Support directory
- Remove from `~/Library/Application Scripts` - all directories started with **com.adguard.safari** and **TC3Q7MAJXF.com.adguard.safari.AdGuard** folder
- Remove from `~/Library/Containers` - all directories started with **AdGuard-**
- Remove **TC3Q7MAJXF.com.adguard.safari.AdGuard** folder from `~/Library/GroupContainers` directory
- Remove **com.adguard.safari.AdGuard.plist** from `~/Library/Preferences`
4. Quit all `AdGuard` and `cfprefsd` processes from Activity monitor
5. Quit Safari.
6. Reinstall AdGuard for Safari

**Comment by windwak3r** [comment] 2024-10-23 14:29
@sammichaels any updates?

**Comment by windwak3r** [comment] 2024-12-04 16:29
@sammichaels We'll close the issue for now. Please leave a comment if the problem is still relevant.

**Closed** 2024-12-04 16:29 UTC
Labels: Bug, waiting for data, Priority: P4
