### ISSUE TITLE
Splash screen at statrup

### ISSUE THREAD

**Issue by JamesKayten** [AdguardTeam/AdGuardForSafari#815] opened 2023-02-26 17:33 UTC

**Comment by JamesKayten** [comment] 2023-02-26 17:34
Is there a way to not have the large settings screen appear every time I start up my machine?

<img width="1708" alt="image" src="https://user-images.githubusercontent.com/7013619/221426615-4f1e123d-ad5b-4222-a1bf-c01755745bf0.png">

**Comment by Versty** [comment] 2023-02-27 08:22
@JamesKayten 
We are aware of the issue and are currently working on a fix.
As a temporary solution you can uninstall, then download and install the version from [this link](https://agrd.io/safari_release).

Closed as a duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/805

**Closed** 2023-02-27 08:23 UTC
Labels: Duplicate
