### ISSUE TITLE
No auto launch after reboot

### ISSUE THREAD

**Issue by kevinchan0903** [AdguardTeam/AdGuardForSafari#333] opened 2020-03-25 05:03 UTC
Device:
macOS 10.15.4
AdGuard for Safari 1.7.2

I have checked "Launch AdGuard for Safari at Login". After rebooting my Macbook Air, it doesn't auto-launch. In Safari, the icon of AdGuard is a Pause sign that it indeed is not running.

**Comment by zecanard** [comment] 2020-03-25 06:40
Same here.

**Comment by Mizzick** [comment] 2020-03-26 11:38
Looks like a duplicate of #331

**Closed by Mizzick** 2020-03-26 11:38 UTC
Labels: Bug, P2: High
