### ISSUE TITLE
AdGuard for Safari always opening control panel after reboot/relogon

### ISSUE THREAD

**Issue by Madd33n** [AdguardTeam/AdGuardForSafari#201] opened 2019-07-09 16:58 UTC
### Steps to reproduce
1. Set "Start AdGuard for Safari at login" to YES
2. Reboot your Mac
3. After rebooting Adguard automatically opens the preference panel on every restart - also after setting "Invisible" on Mac system preferences / Users / Loginobjects (may wording not correct because I use a german MacOs. 
4.

### Expected behavior
Starting the app on logon must be complete invisble - as any other application. 
If not implemented as default there must be a switch in the preferences to start the application in background without opening the preference-pane.

### Actual behavior
After rebooting Adguard automatically opens the preference panel on every restart. 

<details><summary>Screenshots:</summary>

![Bildschirmfoto 2019-07-09 um 18 52 22](https://user-images.githubusercontent.com/46282808/60908030-37a8d780-a27b-11e9-8e37-4144eeac03e1.png)

</details>

### Your environment
* AdGuard for Safari version: 1.3.4
* Environment name and version: Safar 12.1.1
* Operating System: macOS Mojave 10.14.5
* Filters you use in AdGuard: PopUp-Blocker, Datasecurity/Privacy, Security and Others
* Any other browser extensions you have installed: 1Password and Cascadea

**Comment by zzebrum** [comment] 2019-07-09 17:30
closed as a duplicate of #141 please, try the latest [beta](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.4.1-beta) or wait until v1.4.1 will be released in appstore.

**Comment by gpoplin1** [comment] 2023-03-03 07:40
So I was wrong.
Today it took 5 hours and 58 min for adguard to open.

Look, I'm not holding any disappreciation for AdGuard- but I'm gonna go with my alternatives. 
I really hope AdGuard get's this figured out, and in the future I'd look at them again. 
But as of right now, there are better competitors that offer a product as good, that doesn't have these problems.

**Closed** 2023-03-06 14:15 UTC
Labels: Duplicate
