### ISSUE TITLE
Youtube lag when scrolling (safari)

### ISSUE THREAD

**Issue by randomguy14** [AdguardTeam/AdGuardForSafari#478] opened 2020-12-05 15:47 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by gnattu** [comment] 2020-12-06 18:45
This might not be related to AdGuard directly, it's more likely Google with improper styling that makes Safari unhappy.
Can you see the scrolling after injecting following CSS rules?

```css
ytd-page-manager {
  overflow-y: unset !important;
}

#page-manager.ytd-app {
  overflow-x: unset !important;
}
```

**Comment by TheHasagi** [comment] 2020-12-06 22:46
@randomguy14 

Duplicate of #469 

Also, check this [comment](https://github.com/AdguardTeam/AdGuardForSafari/issues/469#issuecomment-738015993).

**Closed by TheHasagi** 2020-12-06 22:46 UTC
