### ISSUE TITLE
1.3.4 Safari set to open at startup opens preferences - please set as option or stop:) thanks

### ISSUE THREAD

**Issue by midco** [AdguardTeam/AdGuardForSafari#194] opened 2019-06-24 13:05 UTC
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshots:</summary>

</details>

### Your environment

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

**Comment by midco** [comment] 2019-06-24 13:09
Reproduce: start up iMac ... preferences for adguard show up
Expected: that it does not.  No reason - needs to be user option.
Actual:
this shows up 
![Screen Shot 2019-06-24 at 08 06 20](https://user-images.githubusercontent.com/52164029/60021223-3a8ab200-9657-11e9-91ee-fde447dfa846.png)

THANKS FOR CONSIDERING.  Really prefer Adguard to open then but without preference box.

**Comment by sjmagy** [comment] 2019-06-26 21:04
I second this!

On top of the issue with having to disable almost all filters just to get it below the 50,000 rule limit cap, AdGuard insisting on opening its preferences window on every computer restart has me just about ready to uninstall this.

The settings window does not need to (and should not) open automatically.  It didn't previously (when AdGuard was set to launch at login).  Please restore the prior functionality / fix this.  It's extremely annoying.

**Comment by ameshkov** [comment] 2019-06-26 21:19
Seems like a duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/141

**Closed by ameshkov** 2019-06-26 21:19 UTC
Labels: Duplicate

**Comment by midco** [comment] 2019-06-26 21:29
So does that mean it will be fixed ?
Thanks

On Jun 26, 2019, at 16:19, Andrey Meshkov <notifications@github.com> wrote:

Seems like a duplicate of #141 <https://github.com/AdguardTeam/AdGuardForSafari/issues/141>

**Comment by ameshkov** [comment] 2019-06-26 21:34
@midco sure, it will

**Comment by midco** [comment] 2019-06-26 21:41
sjmagy - for me, the 50,000 rule issue was taken care of when I updated to 1.3.4.

I will say though, that I first verified what was wanting to update as the notice on imac did not clearly identifying plus the ‘icon’ was not Adguard green check mark.  




On Jun 26, 2019, at 16:04, sjmagy <notifications@github.com> wrote:

I second this!

On top of the issue with having to disable almost all filters just to get it below the 50,000 rule limit cap, AdGuard insisting on opening its preferences window on every computer restart has me just about ready to uninstall this.

The settings window does not need to (and should not) open automatically. It didn't previously (when AdGuard was set to launch at login). Please restore the prior functionality / fix this. It's extremely annoying.

**Comment by sjmagy** [comment] 2019-06-26 21:51
For me it's not -- I still get the notification that too many filters are enabled for Safari.  (This if I enable:  Ad Blocking, Privacy, Annoyances, Security, Other, Language-specific, and Custom.)  I have to disable the "Security" filter group to get the count below 50,000, which seems.... unhelpful.

**Comment by ameshkov** [comment] 2019-06-26 21:53
The only way to fix this on our side is to introduce multiple content blockers as explained here: #93 

This is planned on v1.5
