### ISSUE TITLE
Adguard shows and stays in temp part of Dock

### ISSUE THREAD

**Issue by mrmac189** [AdguardTeam/AdGuardForSafari#670] opened 2021-12-12 16:17 UTC
After re-login or rebooting Mac it happens all the time. Adguard seems to be initializing and stays in temporary part of Dock so I need to manually remove it. In settings every 'startup' features is disabled. I found this very annoying and I hope someday it will be fixed. 
I didn't see such problems with Adblock Plus, for example.

**Comment by Birbber** [comment] 2021-12-13 14:19
@mrmac189 What OS and AdGuard version you use?
We couldn't reproduce the issue. Could you record a video of that happening?

**Comment by Birbber** [comment] 2021-12-20 08:11
@mrmac189 Any news?

**Comment by mrmac189** [comment] 2021-12-21 10:34
Hello, this is the same problem as described in this thread. https://github.com/AdguardTeam/AdGuardForSafari/issues/308
Issue is closed, but even last comments proves that problem stays.

**Comment by Birbber** [comment] 2021-12-22 09:47
@mrmac189 I will close this issue, and re-open the one you've mentioned. Thanks for pointing this out.

**Closed by Birbber** 2021-12-22 09:47 UTC
Labels: waiting for data
