### ISSUE TITLE
I see adguard on my goddamn screen every day, sometimes twice a day!

### ISSUE THREAD

**Issue by collectttive** [AdguardTeam/AdGuardForSafari#909] opened 2023-10-08 19:55 UTC
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
- OS: 14.0 (23A344) (doesn't matter, it was the same on the previous OS)
- Safari version: 17.0 (19616.1.27.211.1)

The OS and Safari don't matter here.

I don't want to see your app screen on my screen anymore.

It happens on a daily basis, sometimes even multiple times a day.

Maybe I don't understand something, but where is the option to hide your app from popping up?

Ridiculous!
```

### Issue Details

Steps to reproduce:
1. Download AdGuard
2. Don't do anything
3. ?????
4. Get AdGuard pop up in your face at least once per day

### Actual Behavior

Already described everything.

### Screenshots

https://i2.paste.pics/54868319abd247309053137ef617ccda.png

**Comment by Versty** [comment] 2023-10-09 08:28
@collectttive Duplicate of #853

**Closed** 2023-10-09 08:28 UTC
Labels: Priority: P4

**Comment by collectttive** [comment] 2023-10-14 07:26
> Update to the latest version, it solves this issue.

No it does not. Every morning I open my laptop and see the f adguard screen.
