### ISSUE TITLE
Add an Option to Open AdGuard Minimized

### ISSUE THREAD

**Issue by luxmanifestus** [AdguardTeam/AdGuardForSafari#697] opened 2022-03-31 17:37 UTC
I am using the AdGuard For Safari app for MacOS. I appreciate the option to start AdGuard at login but every time the system boots up, a settings window for the app is produced that I have to manually close, to declutter my desktop, every day. Please add an option to start AdGuard minimized, as many other apps do. Thank you so much.  

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by Birbber** [comment] 2022-04-15 12:55
@luxmanifestus Hi! Could you tell us the system you use?
I've tested on Monterey, but AdGuard for Safari is always run on the background.

**Comment by luxmanifestus** [comment] 2022-04-15 19:02
I am using macOS Monterey 12.3.1 AdGuard does work in the background but the settings window pops up when it launches at login. It is preferable that the window not pop up at all, so that AdGuard works entirely in the background, even after automatically launching after login.

**Comment by Birbber** [comment] 2022-04-18 14:16
This issue looks like a duplicate of [#680](https://github.com/AdguardTeam/AdGuardForSafari/issues/680). 
I will close this one. You can add any additional info in #680 comments.

**Closed** 2022-04-18 14:17 UTC
