### ISSUE TITLE
JS rule works if added to user rules only

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#587] opened 2021-04-29 12:20 UTC
URL for test(check with US VPN)
https://www.cbs.com/shows/the_price_is_right/video/VcAnR3K1zGcohClegiudhvYhTdAjJnw7/the-price-is-right-4-23-2021/
The rule:
`www.cbs.com#%#!function(){function b(){}function a(a){return{get:function(){return a},set:b}}function c(a){a(!1)}AG_defineProperty('_sp_.config.content_control_callback',a(b)),AG_defineProperty('_sp_.config.spid_control_callback',a(b)),AG_defineProperty('_sp_.config.vid_control_callback',a(b)),AG_defineProperty('_sp_.config.disableBlockerStyleSheets',a(!1)),AG_defineProperty('_sp_.checkState',a(c)),AG_defineProperty('_sp_.isAdBlocking',a(c)),AG_defineProperty('_sp_.isAdblocking',a(c)),AG_defineProperty('_sp_.isContentBlockerPresent',a(c)),AG_defineProperty('_sp_.getSafeUri',a(function(a){return a})),AG_defineProperty('_sp_.pageChange',a(b)),AG_defineProperty('_sp_.setupSmartBeacons',a(b)),AG_defineProperty('_sp_.msg.startMsg',a(b)),document.addEventListener('sp.blocking',function(a){a.stopImmediatePropagation(),a=document.createEvent('Event'),a.initEvent('sp.not_blocking',!0,!1),this.dispatchEvent(a)})}();`

It is added to Base filter, but ad blocking is detected when you watch video(~30 seconds).
When this rule is added to user rules, AdGuard is not detected.

**Comment by tvinzz** [comment] 2021-08-30 12:55
can't reproduce for the momet, propably fixed in converter.

**Closed by tvinzz** 2021-08-30 12:55 UTC
Labels: Bug, Medium
