### ISSUE TITLE
AdGaud for Safari 1.8.6 appears to have deleted Extensions

### ISSUE THREAD

**Issue by JuanCab** [AdguardTeam/AdGuardForSafari#436] opened 2020-11-23 20:09 UTC
Just upgraded to AdGuard for Safari 1.8.6 on my High Sierra Mac (macOS 10.13.6) running Safari 13.1.2.  When it launched, it complained that some of the Safari extensions were disabled and offered to open Safari's preferences to have me enable them.  When it did I discovered ONLY THREE AdGuard Extensions appear under Safari's preferences:
- AdGuard Advanced
- AdGuard General
- AdGuard Safari Icon
None of the other extensions appear.  AdGuard is crippled thinking it has only a partial install.  Any ideas?

**Comment by ameshkov** [comment] 2020-11-23 20:11
Duplicate of #419 

Since we started using new Swift version, AG stopped working on High Sierra. We'll fix this in the next update, but for now the only way is to downgrade to 1.8.2: https://github.com/AdguardTeam/AdGuardForSafari/issues/432#issuecomment-731560789

**Closed by ameshkov** 2020-11-23 20:11 UTC
Labels: Duplicate
