### ISSUE TITLE
The scriptlet doesn't apply in iframe

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdGuardForSafari#395] opened 2020-10-29 11:53 UTC
Related to the issue: https://github.com/AdguardTeam/AdguardFilters/issues/66095

`#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "/emZnbG9hZGVk|break;case \$\./")`

This and other scriptlets doesn't work in Safari f.e. on page `https://gogoanime.so/boruto-naruto-next-generations-episode-16` for player `gogo-stream.com` in iframe (I tried this and other scriptlets from user rules too). But if I open `gogo-stream.com/streaming.php?id=OTk1MjE=&title=Boruto%3A+Naruto+Next+Generations+Episode+16` in separate window - scriptlet works good (clickunder doesn't trigger)

Safari Version 14.0 (15610.1.28.1.9, 15610)
MacOS 10.15.7 (19H2) Catalina
AdGuard 1.8.2

**Comment by superlex** [comment] 2020-10-29 17:44
I think this is related to this issue too:
https://github.com/AdguardTeam/AdGuardForSafari/issues/105

**Comment by tvinzz** [comment] 2020-10-29 18:44
it's fixed already. @Sergey-Lyapin try v1.8.3-beta

**Comment by Sergey-Lyapin** [comment] 2020-10-30 07:32
Ok, thank you

**Comment by Sergey-Lyapin** [comment] 2020-10-30 08:04
Looks like the problem is still exists, please check the video:
https://drive.google.com/file/d/1FjmYLm8qcScOfSYOCv_dfS5Zd0fE70Qu/view?usp=sharing

**Comment by Sergey-Lyapin** [comment] 2020-11-03 16:51
still relevant in 1.8.4-beta

**Comment by ameshkov** [comment] 2020-12-01 20:32
@Mizzick any update here?

**Comment by Mizzick** [comment] 2020-12-01 20:41
`#%#//scriptlet('log', 'hello', 'world')`
this one works fine, so I think it's fixed.

**Comment by ameshkov** [comment] 2020-12-01 20:43
Oh, got it, let's close it then.

**Comment by superlex** [comment] 2020-12-01 22:24
@Mizzick @ameshkov 
I think it isn't fixed.
Try
`disqus.com#%#//scriptlet('log', 'hello', 'world')`
On Firefox:
```
https://disqus.com/ -> Yes
https://www.hdblog.it/ -> Yes
```
On Safari:
```
https://disqus.com/ -> Yes
https://www.hdblog.it/ -> Not
```

**Comment by ameshkov** [comment] 2020-12-02 09:51
@Mizzick 

Confirmed. The problem is that when `safari.extension.dispatchMessage('getAdvancedBlockingData');` is called, Safari operates the URL of the top frame instead of the frame URL.

You should pass the URL frame in the parameter.

**Comment by ameshkov** [comment] 2020-12-03 10:27
Regarding Disqus example, I doubt we can make it work in Safari due to this: `Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.`

Other than that, the issue can be considered fixed.

**Comment by superlex** [comment] 2020-12-03 13:48
Uhm ok..

However, there may be other cases, like YouTube:
`youtube.com#%#//scriptlet('log', 'hello', 'world')`

```
https://www.youtube.com/embed/kayaPmkZ9Kg -> Yes
https://andreagaleazzi.com/recensione/recensione-sony-xh90-85/ -> Not
```

Or Dplay:
`dplay.com#%#//scriptlet('log', 'hello', 'world')`
```
https://it.dplay.com/nove/fake-la-fabbrica-delle-notizie/stagione-3-episodio-5-porno-illegale-telegram/embed/
https://attivissimo.blogspot.com/2020/11/altre-due-puntate-di-fake-la-fabbrica.html
```

**Comment by ameshkov** [comment] 2020-12-03 13:59
YT example works in 1.8.9

**Comment by superlex** [comment] 2020-12-03 20:24
Yep, confirmed, they all work :)

**Closed** 2020-12-04 16:29 UTC
Labels: Bug, P3: Medium, Resolution: Fixed, Status: Resolved
