### ISSUE TITLE
AG 4 Safari extensions not loading in Safari

### ISSUE THREAD

**Issue by swoondrones** [AdguardTeam/AdGuardForSafari#994] opened 2024-06-18 22:33 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18 (build 332, CT 2.0.44)

### Environment

```markdown
- OS: macOS 14.5
- Safari version: 17.5

Hi,

This is happened a few times but now I can't find a solution even when I restart. The extensions to block ads disappear in the Safari extensions dialogue box inside Safari settings. I can't get them to reappear. They seem to automatically be blocked out for some reason when I use AdGuard for Safari. This only happened this morning. It seems to be working fine yesterday more or less even though I was getting the Still ads of what would be normal commercials.

This AdGuard for Safari need another update? If not, how do I fix this? And how do I stop it from happening in the future?
```

### Issue Details

It just happens.

### Expected Behavior

All the extensions should appear on the left side of the window, but they are disappearing and then don't come back.

### Actual Behavior

See above.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="948" alt="ZZ 2024-06-19 at 08 24 10" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/76269339/ce29ffcf-9aae-4f48-a599-69816b9480aa">

<img width="1072" alt="ZZ 2024-06-19 at 08 24 32" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/76269339/bd610c72-6711-4bbe-9f95-c4c880f8ee9c">

</details>

### Additional Information

Safari is completely useless without AdGuard for Safari. Please fix it soon.

**Comment by alexx7311** [comment] 2024-06-19 09:23
@swoondrones Hello! There may be a conflict with other extensions. Please try to disable all extensions, reinstall AdGuard for Safari and enable only the extensions of our app.

**Comment by swoondrones** [comment] 2024-06-19 16:35
Hi Alex,

OK. I did that. However, I do not know what conflict existed as I didn’t change any other extension. Adguard for Safari just seemed to kill itself.

Anyway, I did the complete uninstall by removing everything Adguard and reinstalled. 

It seems to be OK.

:)
   F R E D E R I C K   M A L O U F
   X O
   P O   B O X   7 4 3 4      B O N D I   B E A C H   N S W   2 0 2 6     A U S T R A L I A
+ 6 1   4 0 3   9 9 3   6 9 9
How would I define myself? That’s like asking the definition of infinity …




On 19 Jun 2024, at 19:23, alexx7311 ***@***.***> wrote:


@swoondrones <https://github.com/swoondrones> Hello! There may be a conflict with other extensions. Please try to disable all extensions, reinstall AdGuard for Safari and enable only the extensions of our app.

**Comment by alexx7311** [comment] 2024-07-01 08:49
@swoondrones Maybe the problem is related to https://github.com/AdguardTeam/AdGuardForSafari/issues/995
Please try completely uninstalling AdGuard for Safari:

1. Uncheck all AdGuard for Safari extensions in `Safari - Preferences - Extensions`
2. Remove AdGuard for Safari application from Applications folder
3. In Finder press Shift+Command+G and remove following files:
- Remove **AdGuardSafariApp** folder from `~/Library/Application` Support directory
- Remove from `~/Library/Application Scripts` - all directories started with **com.adguard.safari** and **TC3Q7MAJXF.com.adguard.safari.AdGuard** folder
- Remove from `~/Library/Containers` - all directories started with **AdGuard-**
- Remove **TC3Q7MAJXF.com.adguard.safari.AdGuard** folder from `~/Library/GroupContainers` directory
- Remove **com.adguard.safari.AdGuard.plist** from `~/Library/Preferences`
4. Quit all `AdGuard` and `cfprefsd` processes from Activity monitor
5. Quit Safari.
6. Reinstall AdGuard for Safari

**Comment by alexx7311** [comment] 2024-07-16 14:27
Hello! We'll close the issue for now. Please reply if the problem is still relevant.

**Closed** 2024-07-16 14:27 UTC
Labels: Priority: P4
