### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by adrolson** [AdguardTeam/AdGuardForSafari#811] opened 2023-02-24 21:48 UTC
### Issue Details

Don't need the app Icon in the dock when it starts

### Proposed solution

Would be nice to have the app icon to Not show in the Dock on login

### Alternative solution

Have the choice to have it not show in the dock at login

**Comment by Versty** [comment] 2023-03-01 08:21
@adrolson We are working on improvements related to the icon's behaviour after autostart. 

Duplicate of #308.

**Closed** 2023-03-01 08:22 UTC
Labels: Feature request
