### ISSUE TITLE
Show AdGuard in menu bar isn't saving

### ISSUE THREAD

**Issue by tsegreto** [AdguardTeam/AdGuardForSafari#119] opened 2019-01-02 09:03 UTC
Show AdGuard in menu bar isn't saving on exit thus isn't loading.

### Steps to reproduce

1. Disable Show AdGuard in menu bar
2. Restart.
3.
4.

### Expected behavior

Not saving
### Actual behavior

Not saving

<details><summary>Screenshots:</summary>

</details>

### Your environment

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

**Comment by ameshkov** [comment] 2019-01-06 18:09
Duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/107

**Closed by ameshkov** 2019-01-06 18:09 UTC
