### ISSUE TITLE
AdGuard opens with the settings page on Mac startup

### ISSUE THREAD

**Issue by hriedler86** [AdguardTeam/AdGuardForSafari#824] opened 2023-03-04 22:12 UTC
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.11

### Environment

```markdown
- OS:13.2.1
- Safari version:16.3
```

### Issue Details

Steps to reproduce:
1. Launch AdGuard for Safari at Login activated
2. Restart Mac
3.

### Expected Behavior

AdGuard launches in the background

### Actual Behavior

Window opens on restart
<img width="1072" alt="Screenshot 2023-03-04 at 23 03 55" src="https://user-images.githubusercontent.com/126989876/222930869-e13805c2-ca05-483f-b7b2-7abaae6cd705.png">

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I use adguard to reduce annoyances, not add new ones ;) tried a reinstall but didn't fix anything

**Comment by patrickrushton** [comment] 2023-03-06 19:30
+1

**Comment by Versty** [comment] 2023-03-07 14:35
@hriedler86 @patrickrushton We are aware if this issue and are already working on the fix. 

Closed as a duplicate of #805.

**Closed** 2023-03-07 14:35 UTC
Labels: Duplicate
