### ISSUE TITLE
Every time I login/restart, the Adguard window appears!

### ISSUE THREAD

**Issue by GreypaX** [AdguardTeam/AdGuardForSafari#788] opened 2023-01-10 07:00 UTC
Every time I login/restart, the Adguard window appears!

**Comment by Versty** [comment] 2023-01-10 07:30
@GreypaX Hi! 
Are you on the latest 1.11.10 version?

**Comment by GreypaX** [comment] 2023-01-10 07:31
> @GreypaX Hi!
> Are you on the latest 1.11.10 version?

Yes, 1.11.10 (build 266, CT 2.0.34)

**Comment by Versty** [comment] 2023-01-10 07:38
@GreypaX Could you please reproduce the issue, remember the exact time when the AdGuard window appears, then collect the logs via in-app option (General tab) and send this file to `apple@adguard.com`? 

Mention reproduce time and issue number `#788` in the subject.

**Comment by GreypaX** [comment] 2023-01-10 07:47
> 

ok, i will do it

**Comment by fungiboletus** [comment] 2023-01-10 08:13
I have the same problem.

Logs look like this:

```
[2023-01-09 09:10:36.299] [info] Trace: loadMainWindow
    at getTrace (/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/main.js:30:15)
    at loadMainWindow (/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/main.js:155:14)
    at /Applications/AdGuard for Safari.app/Contents/Resources/app.asar/main.js:364:17
    at /Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/startup.js:69:21
    at /Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/toolbar-controller.js:292:13
[2023-01-09 09:10:36.441] [info] Loading content blocker.
```

**Comment by GreypaX** [comment] 2023-01-10 08:28
full reinstall adguard, problem solved

**Comment by Versty** [comment] 2023-01-10 08:56
@GreypaX @fungiboletus Have you sent the logs by e-mail?

**Comment by Versty** [comment] 2023-01-16 07:29
@GreypaX @fungiboletus Any updates?

**Comment by fungiboletus** [comment] 2023-01-16 07:32
Not yet. I havn't got the issue again.

**Comment by Versty** [comment] 2023-01-16 07:48
@fungiboletus Have you reinstalled the app?

**Comment by Versty** [comment] 2023-01-23 08:27
@GreypaX @fungiboletus Seems like the issue is resolved by a clean installation. 
If you would like to discuss this further, please continue in #746.

**Closed** 2023-01-23 08:28 UTC
Labels: waiting for data
