### ISSUE TITLE
Disable macOS safari popup

### ISSUE THREAD

**Issue by prophoto** [AdguardTeam/AdGuardForSafari#880] opened 2023-08-22 13:11 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13 

### Environment

```markdown
- OS:13.4
- Safari version:16.5
```

### Issue Details

Every other day your app shows a popup when I unlock my computer or reboot. Nag screens are not good UX. 

### Actual Behavior

Turn off nag screen in code or allow me to do it in prefs.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by prophoto** [comment] 2023-08-28 14:50
bump?

**Comment by onesadlittleboy** [comment] 2023-08-29 13:48
This bug has been reported multiple times and hasn't been fixed. At that point the best solution is to remove Adguard and look for a different blocker.

https://github.com/AdguardTeam/AdGuardForSafari/issues/875
https://github.com/AdguardTeam/AdGuardForSafari/issues/876
https://github.com/AdguardTeam/AdGuardForSafari/issues/853

**Comment by prophoto** [comment] 2023-08-29 13:54
Well thats pretty sad is the project dead?

**Comment by vozersky** [comment] 2023-08-29 15:47
duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/875

**Closed by vozersky** 2023-08-29 15:47 UTC
Labels: Priority: P4

**Comment by prophoto** [comment] 2023-08-29 17:42
Closed, ok since its duplicate. Completed? No.
