### ISSUE TITLE
Adguard for M1 Macs

### ISSUE THREAD

**Issue by MaharnavS** [AdguardTeam/AdGuardForSafari#609] opened 2021-05-29 07:26 UTC
I'm running the latest version for adguard for safari (1.9.13) downloaded from Apple App Store.
The OS version on my M1 MacBook Air is macOS Big Sur 11.4
I have thoroughly checked for any form of software update and have also checked the FAQ section in the app.

### Issue Details
* AdGuard for Safari version: 1.9.13
* Environment name and version: Safari 14.1.1 (16611.2.7.1.4)
* Operating System: macOS Big Sur 11.4
* Filters you use in AdGuard: All adblocking, privacy, annoyances, social, security filters active
* Any other browser extensions you have installed: NA

### Expected Behavior
Adguard for Safari should work natively on Apple Silicon
### Actual Behavior
Adguard for Safari working under Rosetta 2 emulation

### Screenshots
<img width="913" alt="Screenshot 2021-05-29 at 12 54 15 PM" src="https://user-images.githubusercontent.com/77191936/120061925-1fafec00-c07d-11eb-9b8a-79c77e5cd5d0.png">

**Comment by ameshkov** [comment] 2021-05-30 17:12
Duplicate of #493

**Closed by ameshkov** 2021-05-30 17:12 UTC
