### ISSUE TITLE
Adguard for Safar 1.10.4 now crashes in MacOS 12.1

### ISSUE THREAD

**Issue by avincent98144** [AdguardTeam/AdGuardForSafari#671] opened 2021-12-13 23:08 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version YES
- [ ]
- [x] I checked the documentation and found no answer NO ANSWER
- [x] I checked to make sure that this issue has not already been filed HAS NOT

### Issue Details

* AdGuard for Safari version: 1.10.4
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) Safari Tech Preview Release 136 (Safari 15.4, WebKit 17613.1.9.2)
* Operating System: (e.g macOS High Sierra 10.13.6) 12.1
* Filters you use in AdGuard: STOCK
* Any other browser extensions you have installed: NONE

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Expected Behavior

START UP AS NORMAL BUT IT CRASHES EVERY TIME. HOWEVER, OPENING THE EXECUTABLE VIA TERMINAL OPENS IS AS A WORK AROUND

### Actual Behavior
 CRASHES

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Aydinv13** [comment] 2021-12-14 08:30
Could you send a crash report when it happens again? (Console- Crash Reports)

Also, to troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Make sure all Safari content blockers are enabled;
2. Open the extension settings --> **Export logs and system info**;
3. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Birbber** [comment] 2021-12-22 10:10
@avincent98144 Is this issue still reproducible?

**Comment by avincent98144** [comment] 2021-12-22 14:24
Anna, not sure why there are 2 email threads on this same issue.

The log files you requested have been sent again.

This is the most recent email body from me a couple days ago:

"I have since discovered that the issue now intermittent: either they all do not work customized, then, even with out a reboot, they are all of a sudden customized."

**Comment by Birbber** [comment] 2021-12-22 14:41
I will close this one as a duplicate of [#672](https://github.com/AdguardTeam/AdGuardForSafari/issues/672).

**Closed by Birbber** 2021-12-22 14:41 UTC
