### ISSUE TITLE
Settings window pops up randomly

### ISSUE THREAD

**Issue by PlanetaryPaul** [AdguardTeam/AdGuardForSafari#825] opened 2023-03-05 15:04 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.10

### Environment

```markdown
- OS:latest
- Safari version: latest
- M1 MBP
```

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

The Settings window should only open when I want it to.

### Actual Behavior

The Settings window tends to open unexpectedly, not often, but every few days. The last time this happened it interrupted a running Keynote presentation, would you believe. Now that is something I just can't afford to have happening. Besides, it simply should be impossible, regardless of any circumstance whatsoever.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment] 2023-03-06 11:22
@PlanetaryPaul Hi! 
We are aware of this issue and working on the fix. 
Please use the temporary solution described in the https://github.com/AdguardTeam/AdGuardForSafari/issues/746#issuecomment-1454022749 to prevent the settings window pop ups at random times. 

Closed as a duplicate of #746

**Closed** 2023-03-06 11:22 UTC
Labels: Duplicate
