### ISSUE TITLE
App does not start minimised on OS start up

### ISSUE THREAD

**Issue by kosakian** [AdguardTeam/AdGuardForSafari#816] opened 2023-02-27 07:10 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.11 (build 275, CT 2.0.34)

### Environment

```markdown
- OS:Ventura 13.2.1
- Safari version:16.3 (18614.4.6.1.6)
```

### Issue Details

Steps to reproduce:
1. Start up OS
2.
3.

### Expected Behavior

Start minimised on start up

### Actual Behavior

It starts maximised on OS startup (stage manager)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment] 2023-02-27 08:27
@kosakian 
We are aware of the issue and are currently working on a fix.
As a temporary solution you can uninstall, then download and install the version from [this link](https://agrd.io/safari_release).

Closed as a duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/805

**Closed** 2023-02-27 08:27 UTC
Labels: Duplicate
