### ISSUE TITLE
the app window stay open

### ISSUE THREAD

**Issue by droogo** [AdguardTeam/AdGuardForSafari#808] opened 2023-02-24 00:36 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.11 (build 275, CT 2.0.34)

### Environment

```markdown
- OS: macOS Ventura 13.2.1
- Safari version: 16.3
```

### Issue Details

Steps to reproduce:
1.star macOS
2.autorun App
3.windows app don't autoclose

### Actual Behavior

When I restart the mac. the app autorun, then the window of filters and any other information about the app stay open, the window don't auto close after ran the app.

Please fix the autoclose of windows of the app.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by hunte164** [comment] 2023-02-24 15:36
Same.

**Comment by gitington** [comment] 2023-02-25 01:32
Same here – Adguard for Safari v. 1.11.11, macOS Ventura 13.2.1 (22D68), MacBook Pro M1 Max

**Comment by Versty** [comment] 2023-02-27 07:43
@droogo We are aware of the issue and are currently working on a fix. 
As a temporary solution you can uninstall, then download and install the version from [this link](https://agrd.io/safari_release). 

Closed as a duplicate of #805

**Closed** 2023-02-27 07:44 UTC
Labels: Duplicate
