### ISSUE TITLE
Preferences Window opens at EVERY login/restart

### ISSUE THREAD

**Issue by rcarmo** [AdguardTeam/AdGuardForSafari#199] opened 2019-07-04 07:54 UTC
### Steps to reproduce

1. Install AdGuard
2. Settings window appears at every restart without an option to hide it, and I have to close it manually

### Expected behavior

I should never see the settings window unless I explicitly ask for it.

### Actual behavior

It opens on every restart, on all machines I have it installed (an iMac, a MacBook Pro and a MacBook Air), for every user (myself and my family, all four of us).

<details><summary>Screenshots:</summary>

</details>

### Your environment

* AdGuard for Safari version: Version 1.3.4
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) Version 12.1.1 (14607.2.6.1.1)
* Operating System: (e.g macOS High Sierra 10.13.6) Mojave 10.14.5 (18F132)
* Filters you use in AdGuard: Defaults
* Any other browser extensions you have installed: None

**Comment by ameshkov** [comment] 2019-07-04 09:04
Duplicate of #141

**Closed by ameshkov** 2019-07-04 09:04 UTC
