### ISSUE TITLE
 Performance Issues on YouTube and text when i write with AdGuard in Safari

### ISSUE THREAD

**Issue by SoundColor** [AdguardTeam/AdGuardForSafari#954] opened 2024-01-24 17:09 UTC
### AdGuard version

1.11.16

### Browser version

Safari 17.3

### OS version

Monterey 12.7.3

### Issue Details

-Provide a set of steps to reproduce the issue.
-Expected Behavior: Smooth and efficient playback of YouTube videos without delays.
-Actual Behavior: Videos load excessively slowly, with a noticeable lag of about 3 seconds when interacting with the interface.

### Expected Behavior

Much more faster

### Actual Behavior

When I try to play videos on YouTube using Safari version 17.3 on macOS Monterey 12.7.3, I encounter significant performance issues. The videos load excessively slowly, and I also experience a noticeable delay, almost like a "lag" of about 3 seconds, when interacting with the search bar or typing. This problem affects not only my interaction with the interface but also the loading of the videos, which take a long time to start playing. Additionally, I'm using AdGuard version 1.11.16. This slow and inefficient performance significantly impacts my user experience on the platform.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I am very happy until this with adguard, you are the best adblock in safari, i know that you can solve that!! :D

**Comment by Aydinv13** [comment] 2024-01-29 08:23
@SoundColor Hello! 

Your issue was transferred to the right repo

**Comment by alexx7311** [comment] 2024-04-23 11:26
@SoundColor Hello! Is the problem still relevant? Please update AdGuard for Safari to the newest version and check if the problem persists.

**Comment by alexx7311** [comment] 2024-04-27 14:46
@SoundColor We'll close the issue for now. Please leave a comment if the problem is still reproducible.

**Closed** 2024-04-27 15:07 UTC
Labels: Bug, Priority: P4
