### ISSUE TITLE
adguard for safari

### ISSUE THREAD

**Issue by RakeshSamala6** [AdguardTeam/AdGuardForSafari#809] opened 2023-02-24 05:05 UTC
### Issue Details

when im shutdown my macbook after sometime reopen my macbook after entering my password then here show popup for adguard.very very very irritating this feature.please solve this issue.
<img width="1710" alt="Screenshot 2023-02-24 at 10 34 19 AM" src="https://user-images.githubusercontent.com/123914969/221096539-afa4c38b-7093-4307-a752-838ab3639a52.png">

**Comment by Versty** [comment] 2023-02-27 08:10
@RakeshSamala6 Hi! 
We are currently working on the fix. 
As a temporary solution you can uninstall, then download and install the version from [this link](https://agrd.io/safari_release).

Closed as a duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/805

**Closed** 2023-02-27 08:12 UTC
Labels: Duplicate
