### ISSUE TITLE
OS Monterey

### ISSUE THREAD

**Issue by midco** [AdguardTeam/AdGuardForSafari#660] opened 2021-11-13 22:42 UTC
### Issue Details

On Nob 12, 2021 I download the latest iMac update.  It was for OSMonterey. It appears that this operating system is using your data for sites that that are allowed and keeping, at least some in history even though Safari is set to Not save cookies and to Delete all history at closure.  The only time, it does Not do this is for 3 sites that I have checked for 'Pause on this website" that is kept under the filter "ALLOW".
I run Safari in Private mode only.  All History and cookies are deleted upon closure of safari - until now.  Cookies are deleted and history is at least partially kept.  I had thought it might be connected to iCloud - which I do Not use nor sing into.  But it is Only when one of the 3 sites in the allow list are the last, ie, most recent, that safari does NOT feel these.

* AdGuard for Safari version:   Version 1.10.4
* Environment name and version: Safari Version 15.1 (17612.2.9.1.20) - It runs in PRIVATE MODE.
* Operating System: (OSMonterey)
* Filters you use in AdGuard: all 6
* Any other browser extensions you have installed: None

*
### Expected Behavior
Prior to OS MONterey, all cookies and ALL history were deleted at closure which I do frequently.
### Actual Behavior
Since OS Monterey, cookies are deleted and some history is but not all BUT if a site is on the "allow" filter, these are Not kept.  A nefarious backwards useage of AdGuard.

THANKS!

**Comment by Birbber** [comment] 2021-11-15 09:39
@midco Hi! We couldn't reproduce the issue on our end. Do you use Private relay?
In general Safari settings it's only possible to set "Remove when Safari quits" for downloads, but not for history items.
Where do you check those parts of data which weren't deleted? How can we reproduce it?

**Comment by Birbber** [comment] 2021-11-22 08:15
@midco Any news?

**Comment by midco** [comment] 2021-11-22 16:47
Hi Anna,
I sent a response but don’t know what happened to it.  Sorry if that was on my end …

I have no clue what ’private relay' is.

Issue left shortly after I submitted. That is Not for the first time.  Perhaps they monitor for bugs in new OS.

You were right about history not allowing for clean out. 
My work around has worked saince I came back to imac.
open a new home page tab then close all other tabs and then quit safari - that most often stops history saves.

Thanks for checking back, much appreciated.
Issue is settled for me.

Alice

**Comment by Birbber** [comment] 2021-11-23 08:26
Thanks for your response. I'm closing the issue now. Please re-open it if needed or add more information if you discover something about it.

**Closed** 2021-11-23 08:26 UTC

**Comment by midco** [comment] 2022-01-06 23:32
Anna,
I hope you get this :)
First update to Monterey helped in that privacy was enacted in part and adguard worked better.  
Monterey 12.1 finished the issue so Private in safari means Private and No history is kept and adguard works as designed.  Some sites are getting wily in that they keep being an ad back - I suppose with minute tweaks but none of them are sufficient for me returning to.   
So keeping on this was welcome.  Thank you so much and May 2022 bring unexpected joys.
Alice
