### ISSUE TITLE
AdGuardForSafari listed as "Using Significant Energy" / High Performance GPU

### ISSUE THREAD

**Issue by patrickrushton** [AdguardTeam/AdGuardForSafari#165] opened 2019-05-18 16:16 UTC
Clicking on the battery icon on macOS always lists AdGuardForSafari as "Using Significant Energy". Activity Monitor doesn't show the process as having significant energy impact, but it is the only app that has "Yes" in the column "Requires High Perf GPU". 

So my guess is this is why it's listed as a battery slurper, since the discreet graphics on my Macbook Pro uses more battery power.

My technical knowledge is limited, but I understand that Electron/Chromium apps can be configured to disable gpu/disable hardware acceleration. Perhaps this is worth looking at?

https://github.com/electron/electron/issues/13303

**Comment by ameshkov** [comment] 2019-05-20 08:55
Yeah, seems to be a duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/110

**Closed by ameshkov** 2019-05-20 08:55 UTC
