### ISSUE TITLE
VK.com Scroll bugged

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardForSafari#473] opened 2020-12-02 22:37 UTC
AdGuard for Safari version: 1.8.8
Environment name and version: 14.0.1 (16610.2.11.51.8)
Operating System: 11.0.1 (20B29)

When scrolling, there are Freezes on vk.com with the AdGuard for Safari extension enabled.
If you turn off Adguard in the Safari extensions menu, there is no Freeze. 
Freezes only occur at the top of the page (noted on site photos).

<img width="998" alt="Houston, we have a problem" src="https://user-images.githubusercontent.com/62497891/100939790-3115a280-34f7-11eb-998f-cdba28becc07.png">
<img width="986" alt="Grigori Schurawi" src="https://user-images.githubusercontent.com/62497891/100939800-37a41a00-34f7-11eb-80ec-757303146127.png">

**Comment by ameshkov** [comment] 2020-12-03 08:06
Duplicate of #469

**Closed by ameshkov** 2020-12-03 08:06 UTC
Labels: Duplicate
